### ISSUE TITLE
Blocked by Please answer the CAPTCHA

### ISSUE THREAD

**Issue by cybercyst** [saik0/humblebundle-python#11]
I followed the example and am blocked by a CAPTCHA request:

> > > import humblebundle
> > > client = humblebundle.HumbleApi()
> > > client.login("******_", "**_*****_")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python3.5/site-packages/humblebundle/decorators.py", line 20, in wrap
> > >     result = func(_args, **kwargs)
> > >   File "/usr/lib/python3.5/site-packages/humblebundle/client.py", line 115, in login
> > >     return handlers.login_handler(self, response)
> > >   File "/usr/lib/python3.5/site-packages/humblebundle/handlers.py", line 76, in login_handler
> > >     captcha_required=captcha_required, authy_required=authy_required)
> > > humblebundle.exceptions.HumbleCaptchaException: Please answer the CAPTCHA

I'm not sure how to get past this error... Any suggestions?

**Comment by saik0** [comment]
Are you on master/v1.1?

**Comment by jmtd** [comment]
I hit this with master (=32bb05c42979ac3de6d8abf103825412e473dfc9) but not immediately, only after the third attempt to run the script.
