### ISSUE TITLE
Is the libary broken?

### ISSUE THREAD

**Issue by k0pper** [saik0/humblebundle-python#17]
Even basic usage doesn't work at all.

```
import humblebundle

client = humblebundle.HumbleApi()

client.search_store("ftl")
```

raises me an HumbleParseException:

> Traceback (most recent call last):
>   File "Home.py", line 5, in <module>
>     client.search_store("ftl")
>   File "/anaconda3/lib/python3.7/site-packages/humblebundle/decorators.py", line 20, in wrap
>     result = func(*args, **kwargs)
>   File "/anaconda3/lib/python3.7/site-packages/humblebundle/client.py", line 239, in search_store
>     return handlers.store_products_handler(self, response)
>   File "/anaconda3/lib/python3.7/site-packages/humblebundle/handlers.py", line 169, in store_products_handler
>     data = parse_data(response)
>   File "/anaconda3/lib/python3.7/site-packages/humblebundle/handlers.py", line 23, in parse_data
>     raise HumbleParseException("Invalid JSON: %s", str(e), request=response.request, response=response)
> humblebundle.exceptions.HumbleParseException: [Errno Invalid JSON: %s] Extra data: line 1 column 5 (char 4)

Is the library deprecated?

**Comment by MCMic** [comment]
It seems the login page moved from login to processlogin.
But fixing this brings: humblebundle.exceptions.HumbleCaptchaException: Are you sure you're not a robot? Please try again.

It seems other softwares are instead asking the user for an auth cookie instead of a login/password, for instance https://github.com/MayeulC/hb-downloader
