### ISSUE TITLE
Invalid JSON error when logging in

### ISSUE THREAD

**Issue by hagabaka** [saik0/humblebundle-python#9]
When I call client.login as example.py does, I get the following error. Replacing the credentials with my own doesn't fix the problem.
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/humblebundle/handlers.py", line 21, in parse_data
    return response.json()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.4/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples.py", line 12, in <module>
    client.login("username@example.com", "secret")
  File "/usr/lib/python3.4/site-packages/humblebundle/decorators.py", line 20, in wrap
    result = func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/humblebundle/client.py", line 112, in login
    return handlers.login_handler(self, response)
  File "/usr/lib/python3.4/site-packages/humblebundle/handlers.py", line 62, in login_handler
    data = parse_data(response)
  File "/usr/lib/python3.4/site-packages/humblebundle/handlers.py", line 23, in parse_data
    raise HumbleParseException("Invalid JSON: %s", str(e), request=response.request, response=response)
humblebundle.exceptions.HumbleParseException: [Errno Invalid JSON: %s] Expecting value: line 1 column 1 (char 0)
```

**Comment by hagabaka** [comment]
I was actually trying to figure out how to script the login process myself. It looks like the /login page returns a HTML file which contains four hidden inputs `_le_csrf_token=...`, which seems to be important, `script-wrapper=login_callback` and `goto=#` which seem to be used for updating the UI depending on login result, and `qs` which is empty. Clicking on the submit button POSTs to `/processLogin`, sending `username`, `password` as well as the hidden inputs.

I tried to emulate this with curl, and I do get a `_simpleauth_sess` cookie, but when I try to GET `/home` with the cookie, I still get the flash 'You must sign in'.
